export const AUTH_ERRORS = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
} as const;

export const RECIPE_ERRORS = {
  RECIPE_NOT_FOUND: "RECIPE_NOT_FOUND",
  RECIPE_NOT_PUBLISHED: "RECIPE_NOT_PUBLISHED",
  RECIPE_FORBIDDEN: "RECIPE_FORBIDDEN",
  RECIPE_LIMIT_FREE: "RECIPE_LIMIT_FREE",
  RECIPE_LIMIT_PREMIUM: "RECIPE_LIMIT_PREMIUM",
  RECIPE_OWNER_CHANGE: "RECIPE_OWNER_CHANGE",
  SAVED_RECIPE_LIMIT: "SAVED_RECIPE_LIMIT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INVALID: "USER_INVALID",
} as const;

export const COMMENT_ERRORS = {
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_FORBIDDEN: "COMMENT_FORBIDDEN",
  RECIPE_NOT_FOUND: "RECIPE_NOT_FOUND",
  RECIPE_NOT_PUBLISHED: "RECIPE_NOT_PUBLISHED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;

export const COMMUNITY_ERRORS = {
  POSTS_NOT_FOUND: "POSTS_NOT_FOUND",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  POST_UPDATE_FORBIDDEN: "POST_UPDATE_FORBIDDEN",
  POST_DELETE_FORBIDDEN: "POST_DELETE_FORBIDDEN",
  ANNOUNCEMENT_FORBIDDEN: "ANNOUNCEMENT_FORBIDDEN",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;

export const CHAT_ERRORS = {
  CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
  CHAT_FORBIDDEN: "CHAT_FORBIDDEN",
  CHAT_LIMIT_REACHED: "CHAT_LIMIT_REACHED",
  CHAT_TITLE_SAME: "CHAT_TITLE_SAME",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;

export const AI_ERRORS = {
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  CHAT_LIMIT_REACHED: "CHAT_LIMIT_REACHED",
} as const;

export const STRIPE_ERRORS = {
  STRIPE_PRODUCTS_FETCH_FAILED: "STRIPE_PRODUCTS_FETCH_FAILED",
  STRIPE_CUSTOMERS_FETCH_FAILED: "STRIPE_CUSTOMERS_FETCH_FAILED",
  STRIPE_CUSTOMER_NOT_FOUND: "STRIPE_CUSTOMER_NOT_FOUND",
  STRIPE_CUSTOMER_ALREADY_EXISTS: "STRIPE_CUSTOMER_ALREADY_EXISTS",
  STRIPE_CUSTOMER_CREATE_FAILED: "STRIPE_CUSTOMER_CREATE_FAILED",
  STRIPE_INVALID_SUBSCRIPTION_REQUEST: "STRIPE_INVALID_SUBSCRIPTION_REQUEST",
  STRIPE_SUBSCRIPTION_CREATE_FAILED: "STRIPE_SUBSCRIPTION_CREATE_FAILED",
  STRIPE_INVALID_PAYMENT_METHOD: "STRIPE_INVALID_PAYMENT_METHOD",
  STRIPE_INVALID_CUSTOMER_DATA: "STRIPE_INVALID_CUSTOMER_DATA",
  STRIPE_PAYMENT_METHOD_ATTACH_FAILED: "STRIPE_PAYMENT_METHOD_ATTACH_FAILED",
  STRIPE_INVALID_PRICE_ID: "STRIPE_INVALID_PRICE_ID",
  STRIPE_PAYMENT_LINK_CREATE_FAILED: "STRIPE_PAYMENT_LINK_CREATE_FAILED",
} as const;
