/**
 * Mock recipe data used for development and testing.
 */

import { food } from "@/assets";
import type { Recipe } from "./types";

/**
 * Array of mock recipes with detailed information.
 * Repeated entries simulate a larger database for pagination/list views.
 */
export const mockRecipes: Recipe[] = [
  {
    id: "recipe_1",
    title: "Creamy Mushroom Risotto",
    description: "A delicious and creamy vegan mushroom risotto",
    imageUrl: food,
    ingredients: [
      "2 cups arborio rice",
      "500g mushrooms",
      "1 onion",
      "3 cups vegetable broth",
      "1 cup white wine",
      "Nutritional yeast",
      "Fresh herbs",
    ],
    instructions: [
      "Sauté onions and mushrooms",
      "Add rice and toast for 2 minutes",
      "Add wine and let it absorb",
      "Add broth gradually, stirring constantly",
      "Finish with nutritional yeast and herbs",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "medium",
    tags: ["vegan", "italian", "comfort-food"],
    userId: "user_1",
    user: {
      name: "Emma Johnson",
      avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    rating: 4.8,
    views: 1320,
    isFavorite: true,
    createdAt: "2024-05-10T12:00:00Z",
    updatedAt: "2024-05-10T12:00:00Z",
  },
  {
    id: "recipe_2",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_3",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_33",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_4",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_5",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_6",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_7",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_8",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_9",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_10",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
  {
    id: "recipe_11",
    title: "Spicy Thai Noodles",
    description: "Quick and spicy Thai-inspired noodle dish",
    imageUrl: food,
    ingredients: [
      "200g rice noodles",
      "2 tbsp peanut butter",
      "2 tbsp soy sauce",
      "1 tbsp sriracha",
      "Vegetables (bell peppers, carrots)",
      "Peanuts for garnish",
    ],
    instructions: [
      "Cook noodles according to package",
      "Mix peanut butter, soy sauce, and sriracha",
      "Stir-fry vegetables",
      "Toss everything together",
      "Garnish with peanuts",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    tags: ["vegan", "asian", "quick"],
    userId: "user_2",
    user: {
      name: "Liam Smith",
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    rating: 3.2,
    views: 875,
    isFavorite: false,
    createdAt: "2024-05-15T14:30:00Z",
    updatedAt: "2024-05-15T14:30:00Z",
  },
];
